
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: postgresql://localhost:5432/wre_code_challenge_development

test:
  <<: *default
  url: postgresql://localhost:5432/wre_code_challenge_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: blog
